currencies = ['BTC', 'ETH', 'BNB', 'XRP', 'ADA', 'STETH', 'DOGE', 'MATIC', 'SOL', 'DOT', 'LTC', 'SHIB', 'TRX', 'AVAX',
              'UNI', 'LINK', 'ATOM', 'TONCOIN', 'OKB', 'XMR', 'ETC', 'XLM', 'ICP', 'BCH', 'FIL', 'APT', 'HBAR', 'CRO',
              'LDO', 'ARB', 'NEAR', 'VET', 'QNT', 'APE', 'ALGO', 'GRT', 'FTM', 'XRD', 'EOS', 'EGLD', 'SAND', 'AAVE',
              'IMX', 'STX', 'MANA', 'THETA', 'XTZ', 'FLOW', 'CFX', 'RPL', 'AXS', 'RNDR', 'SNX', 'NEO', 'CRV', 'INJ',
              'KLAY', 'OP', 'CHZ', 'BSV', 'LUNC', 'GMX', 'MKR', 'FXS', 'MINA', 'BTT', 'CSPR', 'XEC', 'XDC', 'DASH',
              'IOTA', 'KAS', 'PAXG', 'CAKE', 'WOO', 'RETH', 'TWT', 'XAUT', 'ZIL', 'OSMO', 'FLR', 'LRC', 'BABYDOGE',
              'AGIX', 'DYDX', 'RUNE', 'CVX', 'KAVA', '1INCH', 'ENJ', 'NEXO', 'AR', 'BAT', 'FLOKI', 'ZEC', 'FET', 'MASK',
              'HOT', 'XEM', 'DFI', 'SXP', 'ROSE', 'LUNA', 'ETHW', 'JASMY', 'ENS', 'AUDIO', 'WEMIX', 'BLUR', 'ANKR',
              'AZERO', 'TFUEL', 'QTUM', 'CELO', 'GALA', 'XCH', 'ERXETH', 'RVN', 'BDX', 'OHM', 'ASTR', 'ICX', 'GNO',
              'DCR', 'COMP', 'KSM', 'YFI', 'T', 'LN', 'ILV', 'HNT', 'MAGIC', 'OME', 'BTG', 'BAL', 'ONT', 'BONE', 'IOTX',
              'DAO', 'GMT', 'GLM', 'LYXE', 'RON', 'JST', 'ZRX', 'KRD', 'GLMR', 'BAND', 'ID', 'KDA', 'SUSHI', 'SC',
              'AMP', 'IOST', 'WAVES', 'SSV', 'HIVE', 'BICO', 'GNS', 'OMI', 'MULTI', 'FLUX', 'EXRD', 'TOMI', 'SKL',
              'POLY', 'JOE', 'BORA', 'XYM', 'CTSI', 'CHSB', 'ACH', 'LQTY', 'BNX', 'SFP', 'XIN', 'OCEAN', 'SYN', 'BRISE',
              'ACS', 'EVMOS', 'LPT', 'BLID', 'KUB', 'TEL', 'DGB', 'OMG', 'TRAC', 'DESO', 'STRD', 'STG', 'CELR', 'CKB',
              'DHX', 'LSK', 'COMBO', 'UMA', 'APPI3', 'POLYX', 'ZEN', 'ELF', 'ANT', 'TRIBE', 'CANTO', 'SCRT', 'RIF',
              'EWT', 'CEL', 'METIS', 'PLA', 'KNC', 'DEXE', 'RLC', 'MIM', 'WAXL', 'HFT', 'SLP', 'ERG', 'EVER', 'FXS',
              'SGB', 'RDNT', 'ALICE', 'XNO', 'HOOK', 'MC', 'MSOL', 'PEOPLE', 'SNT', 'C98', 'RBN', 'SYS', 'FLEX', 'NMR',
              'ABBC', 'ALICE', 'MLK', 'GTC', 'LOCUS', 'BLD', 'MRS', 'COTI', 'MBOX', 'DENT', 'REN', 'ORBS', 'DERO',
              'GLR', 'KWENTA', 'XVS', 'RAD', 'SFM', 'CFG', 'DAG', 'WCFG', 'PROM', 'STEEM', 'CHR', 'ARDR', 'DKA', 'ASD',
              'MED', 'CQT', 'IQ', 'VTHO', 'AVINOC', 'PYR', 'KEEP', 'CVC', 'GAL', 'NYM', 'STIK', 'NEST', 'WIN', 'HEZ',
              'KUJI', 'STRAX', 'TOMO', 'POND', 'MOB', 'BNT', 'PHA', 'UOS', 'MTL', 'CORE', 'MDX', 'MBX', 'POWR', 'BFC',
              'WRX', 'CWEB', 'VGX', 'HUNT', 'CEEK', 'QKC', 'BOBA', 'REQ', 'NKN', 'DUSK', 'DOLA']
